import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { activities, approvals as initialApprovals, changes, files, goal as initialGoal, messages as initialMessages, tasks as initialTasks, terminalEntries, testResults, timeline } from "./data/demo";
import { ApprovalsPage } from "./pages/ApprovalsPage";
import { ChangesPage } from "./pages/ChangesPage";
import { ChatPage } from "./pages/ChatPage";
import { FilesPage } from "./pages/FilesPage";
import { GoalPage } from "./pages/GoalPage";
import { GoalBuilderPage } from "./pages/GoalBuilderPage";
import { PlanPage } from "./pages/PlanPage";
import { SettingsPage } from "./pages/SettingsPage";
import { TasksPage } from "./pages/TasksPage";
import { TerminalPage } from "./pages/TerminalPage";
import { TestsPage } from "./pages/TestsPage";
import { TimelinePage } from "./pages/TimelinePage";
import { WorkspacePage } from "./pages/WorkspacePage";
import { WebSocketManager, type ConnectionState } from "./services/websocket/WebSocketManager";
import { GoalClient } from "./services/api/GoalClient";
import type { Activity, Approval, ChatMessage, CodexQuestion, Goal, Task, Theme } from "./types/codex";
const navigation = [{ label: "Workspace", icon: "◈", path: "/" }, { label: "Chat", icon: "◌", path: "/chat" }, { label: "Goal", icon: "◎", path: "/goal" }, { label: "Plan", icon: "⌘", path: "/plan" }, { label: "Tasks", icon: "✓", path: "/tasks" }, { label: "Files", icon: "▱", path: "/files" }, { label: "Changes", icon: "↗", path: "/changes" }, { label: "Terminal", icon: ">_", path: "/terminal" }, { label: "Tests", icon: "⚗", path: "/tests" }, { label: "Approvals", icon: "!", path: "/approvals" }, { label: "Timeline", icon: "◷", path: "/timeline" }, { label: "Settings", icon: "◐", path: "/settings" }, { label: "New goal", icon: "+", path: "/new" }] as const;
type View = (typeof navigation)[number]["label"];
const pendingQuestion: CodexQuestion = { id: "security-mode", goalId: "goal_aurora", type: "radio", title: "Which remote-access model should we use?", description: "This determines how we design identity and device authorization.", required: true, options: [{ label: "Local only", value: "local" }, { label: "Local + opt-in cloud", value: "hybrid" }, { label: "Cloud managed", value: "cloud" }] };
const mockMode = import.meta.env.VITE_USE_MOCKS !== "false";
const emptyGoal: Goal = { id: "", title: "Loading goal…", objective: "Waiting for authoritative Codex state.", status: "draft", progress: 0, requirements: [], successCriteria: [] };
const headings: Record<View, [string, string, string]> = { Workspace: ["EXECUTION OVERVIEW", "Good morning, Salline.", "Your goal is actively progressing. Here’s what matters right now."], Chat: ["CONVERSATION", "Stay in the loop.", "Give Codex decisions, feedback, and new direction without losing goal context."], Goal: ["GOAL WORKSPACE", "Shape the outcome.", "Review scope, requirements, and the conditions that must be verified."], Plan: ["PLAN", "See the route to done.", "Tasks, dependencies, and execution state are always driven by Codex."], Tasks: ["TASK QUEUE", "Inspect the work.", "Open a task to see its useful execution summary and affected files."], Files: ["PROJECT", "Browse the repository.", "Files are loaded on demand rather than copied into your browser."], Changes: ["REVIEW", "Understand each change.", "Review proposed modifications before approving anything sensitive."], Terminal: ["EXECUTION OUTPUT", "Follow command activity.", "Codex streams backend execution safely; this browser never executes commands."], Tests: ["VERIFICATION", "Trust the evidence.", "A goal is complete only after the backend verifies its success criteria."], Approvals: ["SECURITY CHECKPOINT", "Make decisions explicitly.", "Review exactly what Codex is requesting before authorizing sensitive work."], Timeline: ["ACTIVITY HISTORY", "See the whole story.", "Follow the decisions and state changes that move your goal toward verification."], Settings: ["PREFERENCES", "Make the workspace yours.", "Choose appearance, model routing preferences, and notification behavior."], "New goal": ["GOAL BUILDER", "What would you like to build?", "Start with an idea; Codex will help you make it executable."] };
export default function App() { const location = useLocation(); const navigate = useNavigate(); const view = navigation.find((item) => item.path === location.pathname)?.label ?? "Workspace"; const [theme, setTheme] = useState<Theme>((localStorage.getItem("theme") as Theme) || "system"); const [connection, setConnection] = useState<ConnectionState>(mockMode ? "connected" : "connecting"); const [goal, setGoal] = useState<Goal>(mockMode ? initialGoal : emptyGoal); const [tasks, setTasks] = useState<Task[]>(mockMode ? initialTasks : []); const [messages, setMessages] = useState<ChatMessage[]>(mockMode ? initialMessages : []); const [activity, setActivity] = useState<Activity[]>(mockMode ? activities : []); const [approvals, setApprovals] = useState<Approval[]>(mockMode ? initialApprovals : []); const [draft, setDraft] = useState(""); const [paused, setPaused] = useState(false); const [question, setQuestion] = useState<CodexQuestion | undefined>(mockMode ? pendingQuestion : undefined); const ws = useRef<WebSocketManager | null>(null); const lastSequence = useRef(-1); const [eyebrow, title, description] = headings[view];
 useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("theme", theme); }, [theme]);
 useEffect(() => { if (mockMode) return; ws.current = new WebSocketManager(import.meta.env.VITE_CODEX_WS_URL ?? "ws://localhost:8787/ws", setConnection); const unsubscribe = ws.current.subscribe((event) => { if (event.sequence !== undefined && event.sequence <= lastSequence.current) return; if (event.sequence !== undefined) lastSequence.current = event.sequence; if (event.type === "goal.snapshot") { setGoal(event.snapshot.goal); setTasks(event.snapshot.tasks); setMessages(event.snapshot.messages ?? []); setActivity(event.snapshot.activity ?? []); setQuestion(event.snapshot.questions?.[0]); lastSequence.current = event.snapshot.serverSequence; } if (event.type === "task.progress") setTasks((items) => items.map((task) => task.id === event.task_id ? { ...task, progress: event.progress, summary: event.message, status: "running" } : task)); if (event.type === "task.completed") setTasks((items) => items.map((task) => task.id === event.task_id ? { ...task, status: "completed", progress: 100 } : task)); if (event.type === "goal.updated") setGoal((current) => ({ ...current, ...event.goal })); if (event.type === "question.created") setQuestion(event.question); if (event.type === "activity") setActivity((items) => [event.activity, ...items]); }); ws.current.connect(); return () => { unsubscribe(); ws.current?.disconnect(); }; }, []);
 useEffect(() => { if (mockMode || connection !== "connected") return; const goalId = import.meta.env.VITE_CODEX_GOAL_ID; if (!goalId) return; let active = true; void new GoalClient().getState(goalId).then((snapshot) => { if (!active) return; lastSequence.current = snapshot.serverSequence; setGoal(snapshot.goal); setTasks(snapshot.tasks); setMessages(snapshot.messages ?? []); setActivity(snapshot.activity ?? []); setQuestion(snapshot.questions?.[0]); }).catch(() => { if (active) setActivity((items) => [{ id: crypto.randomUUID(), time: "Now", kind: "warning", text: "Could not synchronize the current goal state." }, ...items]); }); return () => { active = false; }; }, [connection]);
 const addActivity = (text: string, kind: Activity["kind"] = "working") => setActivity((items) => [{ id: crypto.randomUUID(), time: "Now", kind, text }, ...items]);
 const send = () => { if (!draft.trim()) return; const content = draft.trim(); setMessages((items) => [...items, { id: crypto.randomUUID(), role: "user", content, time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }]); ws.current?.send({ type: "chat.message", goal_id: goal.id, content }); setDraft(""); addActivity("New direction sent to Codex"); };
 const answer = (answerValue: unknown) => { ws.current?.send({ type: "question.answer", question_id: question?.id, answer: answerValue }); setQuestion(undefined); addActivity("Security decision sent to Codex", "success"); };
 const attach = (selectedFiles: FileList | null) => { if (selectedFiles?.length) addActivity(`Attached ${[...selectedFiles].map((file) => file.name).join(", ")}`); };
 const toggleRequirement = (id: string) => setGoal((current) => ({ ...current, requirements: current.requirements.map((requirement) => requirement.id === id ? { ...requirement, checked: !requirement.checked } : requirement) }));
 const addRequirement = (text: string) => setGoal((current) => ({ ...current, requirements: [...current.requirements, { id: crypto.randomUUID(), text, checked: false }] }));
 const createGoal = async (title: string, objective: string) => { if (mockMode) { setGoal({ id: crypto.randomUUID(), title, objective, status: "discovering", progress: 8, requirements: [], successCriteria: [] }); setTasks([]); setMessages([{ id: crypto.randomUUID(), role: "codex", content: "I’m developing your idea into objective, requirements, and success criteria. I’ll ask only the decisions that affect the plan.", time: "Now" }]); setQuestion(undefined); addActivity("New goal created", "success"); navigate("/goal"); return; } const created = await new GoalClient().create({ title, objective }); setGoal(created); setTasks([]); setMessages([]); setQuestion(undefined); ws.current?.subscribeToGoal(created.id); addActivity("New goal created", "success"); navigate("/goal"); };
 const decideApproval = (approvalId: string, decision: "approved" | "rejected") => { ws.current?.send({ type: "approval.decide", approval_id: approvalId, decision }); setApprovals((items) => items.map((approval) => approval.id === approvalId ? { ...approval, status: decision } : approval)); addActivity(`Approval ${decision}`, decision === "approved" ? "success" : "warning"); };
 return <main className="app-shell"><Header goal={goal} theme={theme} connection={connection} onThemeChange={setTheme} onCreateGoal={() => navigate("/new")} /><Sidebar view={view} onNavigate={navigate} /><section className="workspace"><div className="workspace-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{view !== "Settings" && view !== "New goal" && <div className="controls"><button onClick={() => { setPaused(!paused); addActivity(paused ? "Execution resumed" : "Execution paused"); }}>{paused ? "▶ Resume" : "Ⅱ Pause"}</button><button className="danger" onClick={() => window.confirm("Stop this goal? This cancels active tasks.") && setPaused(true)}>■ Stop</button></div>}</div><Page view={view} goal={goal} tasks={tasks} activity={activity} messages={messages} question={question} draft={draft} theme={theme} approvals={approvals} onThemeChange={setTheme} onDraftChange={setDraft} onSend={send} onAnswer={answer} onAttach={attach} onToggleRequirement={toggleRequirement} onAddRequirement={addRequirement} onDecideApproval={decideApproval} onCreateGoal={createGoal} onOpenPlan={() => navigate("/plan")} /></section><Footer paused={paused} progress={goal.progress} /></main> }
function Header({ goal, theme, connection, onThemeChange, onCreateGoal }: { goal: Goal; theme: Theme; connection: ConnectionState; onThemeChange: (theme: Theme) => void; onCreateGoal: () => void }) { return <header className="topbar"><div className="brand"><span className="brand-mark">C</span><span>CODEX <em>WORKSPACE</em></span></div><button className="goal-switcher" onClick={onCreateGoal}><span className="muted">Goal</span><strong>{goal.title}</strong><span>⌄</span></button><div className="top-actions"><span className={`connection ${connection}`}><i />{connection === "connected" ? "Connected" : connection === "reconnecting" ? "Reconnecting…" : "Connection lost"}</span><select aria-label="Theme" value={theme} onChange={(event) => onThemeChange(event.target.value as Theme)}><option value="system">System theme</option><option value="light">Light</option><option value="dark">Dark</option></select><button className="avatar">SL</button></div></header> }
function Sidebar({ view, onNavigate }: { view: View; onNavigate: (path: string) => void }) { return <aside className="sidebar"><nav>{navigation.map((item) => <button key={item.label} className={view === item.label ? "nav-item active" : "nav-item"} onClick={() => onNavigate(item.path)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="agent-card"><span className="eyebrow">ACTIVE AI</span><strong>Automatic routing</strong><p><i className="online" /> Planner · Coding · Tester</p></div></aside> }
function Footer({ paused, progress }: { paused: boolean; progress: number }) { return <footer><span><i className={paused ? "paused" : "online"} />{paused ? "Execution paused" : "Executing"}</span><div className="footer-progress"><i style={{ width: `${progress}%` }} /></div><span>{progress}% complete</span><span className="muted footer-note">Live state from Codex</span></footer> }
type PageProps = { view: View; goal: Goal; tasks: Task[]; activity: Activity[]; messages: ChatMessage[]; question?: CodexQuestion; draft: string; theme: Theme; approvals: Approval[]; onThemeChange: (theme: Theme) => void; onDraftChange: (value: string) => void; onSend: () => void; onAnswer: (answer: unknown) => void; onAttach: (files: FileList | null) => void; onToggleRequirement: (id: string) => void; onAddRequirement: (text: string) => void; onDecideApproval: (approvalId: string, decision: "approved" | "rejected") => void; onCreateGoal: (title: string, objective: string) => Promise<void>; onOpenPlan: () => void; };
function Page(props: PageProps) { switch (props.view) { case "Workspace": return <WorkspacePage goal={props.goal} tasks={props.tasks} activity={props.activity} messages={props.messages} question={props.question} draft={props.draft} onDraftChange={props.onDraftChange} onSend={props.onSend} onAnswer={props.onAnswer} onOpenPlan={props.onOpenPlan} onAttach={props.onAttach} />; case "Chat": return <ChatPage messages={props.messages} draft={props.draft} onDraftChange={props.onDraftChange} onSend={props.onSend} onAttach={props.onAttach} />; case "Goal": return <GoalPage goal={props.goal} onToggleRequirement={props.onToggleRequirement} onAddRequirement={props.onAddRequirement} />; case "Plan": return <PlanPage tasks={props.tasks} />; case "Tasks": return <TasksPage tasks={props.tasks} />; case "Files": return <FilesPage files={files} />; case "Changes": return <ChangesPage changes={changes} />; case "Terminal": return <TerminalPage entries={terminalEntries} />; case "Tests": return <TestsPage results={testResults} />; case "Approvals": return <ApprovalsPage approvals={props.approvals} onDecide={props.onDecideApproval} />; case "Timeline": return <TimelinePage events={timeline} />; case "Settings": return <SettingsPage theme={props.theme} onThemeChange={props.onThemeChange} />; case "New goal": return <GoalBuilderPage onCreate={props.onCreateGoal} />; } }
